Update high_availability_settings for 24.7
puzzle/puzzle.opnsense pull request #149
Opened 2024-08-12 09:13 UTC by LuminatiHD

2024-08-14 07:14 UTC, KiLLuuuhh requested changes
Some small changes but overall very sophisticated update!

2024-08-14 07:14 UTC, KiLLuuuhh commented on plugins/modules/system_high_availability_settings.py
> +def sync_compatibility(config: OPNsenseModuleConfig, compat_version: str):
please define the return value for typing

2024-08-14 07:14 UTC, KiLLuuuhh commented on plugins/module_utils/module_index.py
> +    "24.7": {
please remove this part to avoid merge issues.

2024-08-14 09:42 UTC, LuminatiHD commented on plugins/modules/system_high_availability_settings.py
> +    required: false
[3b9ae7d](https://github.com/puzzle/puzzle.opnsense/pull/149/commits/3b9ae7da3625f509a9afbec9f6ed0ba02dc64ae6)

2024-08-15 06:49 UTC, KiLLuuuhh approved these changes
Looks good to me, great work! :+1:

2024-08-15 08:17 UTC, merged